version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: digitiamo-mysql
    restart: always
    environment:
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DB}"
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - digitiamonetwork
    volumes:
      - mysql_data_digitiamo_db:/var/lib/mysql

  adminer-service:
    image: adminer:latest
    restart: unless-stopped
    container_name: digitiamo-adminer
    depends_on:
      - mysql
    networks:
      - digitiamonetwork
    ports:
      - "8080:8080"

  # fastapi:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: digitiamo-fastapi
  #   restart: unless-stopped
  #   depends_on:
  #     - mysql
  #   ports:
  #     - "8000:8000"
  #     - "5678:5678"
  #   networks:
  #     - digitiamonetwork

  # frontend:
  #   image: digitiamo-frontend
  #   container_name: digitiamo-frontend
  #   restart: unless-stopped
  #   ports:
  #     - "5137:5137"
  #   networks:
  #     - digitiamonetwork

networks:
  digitiamonetwork:

volumes:
  mysql_data_digitiamo_db:
